# Generated by Django 4.0.4 on 2022-05-23 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_card_alter_comment_options_alter_dictionary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации'),
        ),
    ]
