# Generated by Django 4.0.4 on 2023-01-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=60, verbose_name='название проекта')),
                ('project_description', models.TextField(max_length=200, verbose_name='описание проекта')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
